### ISSUE TITLE
New and full Setup for TouchOSC

### ISSUE THREAD

**Issue by mkcologne** [SteffeyDev/atemOSC#167]
Made a full iPad Setup for TouchOSC.
Feel free to use it and change to your needs and have fun!

[You'll find it here](https://github.com/mkcologne/atemMiniTouchOSC)

Cheers - Michael

**Comment by randallpacker** [comment]
This is fantastic!! Thanks so much for sharing.

**Comment by sneat** [comment]
@mkcologne that looks excellent. I don't have access to hardware any more to be able to test it, but would you be happy with it being linked in the readme (and in https://github.com/danielbuechele/atemOSC/tree/master/samples )?

**Comment by carbon43** [comment]
Was looking for a thread to hop on and chime in, and an atemOSC/TouchOSC thread seems like the perfect spot! My 1 M/E is out on a jobbie the upcoming week, so I just ordered an ATEM Mini. This should hopefully let me help out a bit more in fielding ATEM Mini specific queries. Obviously since I do a wee splash of tOSC coding as well I can chime in to field integration questions between the two as well. 

This layout looks awesome btw, looking forward to testing it out.

**Comment by SteffeyDev** [comment]
Added to docs, so closing this issue.  Thanks @mkcologne!

**Comment by mkcologne** [comment]
@SteffeyDev : You're welcome. Will update the Files asap to reflect the new possibilities.
Cheers M.
