### ISSUE TITLE
Hyperdeck play single clip & loop

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#178]
I have been looking through the Protocol Commands for the Hyperdeck Studio, and apparently the "Play" command used by itself defaults at play all clips (Play from current timecode). But there is another command: "Play: Single Clip (true/false), which would allow you to just play one clip without continuing with the next one. 

This functionality is critical, is it possible it can be refined? Many thanks, 

Randall

**Comment by notslaw** [comment]
I would like to echo the above request. We are streaming online and use ATEM OSC to sync up some things with ProPresenter 7 and Ableton Live.  It works really well for the most part.  We are looking to include a pre-service and post-service specific video that will play through a Hyperdeck.  ATEM OSC is triggering play loops true.  When I need to trigger through Ableton Live it wouldn't be much of an issue to send a stop command at the appropriate time.  But since one of those videos is triggered in the middle of a section when Ableton Live isn't being used, and should be the last thing sent to our stream, not having ATEM OSC trigger play loops is an issue for us.  We have to make sure that someone doesn't miss pushing a button at the right time to end the stream without picking up the next clip, which would be the recording of that day's service in most instances.  Would like to know if there is already a solution for this.  I have searched high and low and tried many different things to try to get only a single clip to play back and have had no luck.

**Comment by randallpacker** [comment]
Greetings: I have been using the atemOSC Hyperdeck control extensively and have come up with the following solutions to the constraints. I have created a Macro that play/loops the video. That simple. The problem with the play command in atemOSC is that it is "play through" not "play clip," which means that it will just keep playing through all the remaining clips instead of just the one clip. So my Macro consists of the "play clip" + loop, since there is no atemOSC command for loop. It works great, in fact in Ableton, using VDMX for sending OSC, I have it set it up so that note on's are play/loop, and note off's are stop. That way you can time it very precisely if you have a specific time you want to stop at. 

Randall

**Comment by SteffeyDev** [comment]
Ok, so looking at the SDK I have the ability to toggle a single clip playback mode on and off.  I could set it up so that when you send the `play-clip` command, it toggles the single-clip mode on before playing, and then when you send a normal `play` command, it toggles it off, or I could make it so that you can toggle single-clip mode on and off yourself using a command like `/atem/hyperdeck/#/single-clip <bool>`.  Which would you guys prefer?

**Comment by sneat** [comment]
In my opinion, I like the idea of `play-clip` setting the single-clip mode to on prior to playing.

**Comment by SteffeyDev** [comment]
Adding loop to this issue, considering it is related and I'll put them both in at the same time.  Moving out of #175.

**Comment by notslaw** [comment]
I prefer the idea of being able to set it yourself.  Gives more flexibility for a wider range of playback options.  If you want one clip, you can set single clip.  If you want to play all clips once, you can do that.  If you want to loop, you could set that.  If I remember correctly, I think all three of those were options when I glanced a the SDK a couple of weeks ago.

**Comment by SteffeyDev** [comment]
Should be complete in latest release, 4.0.0. Feel free to re-open if not working right. See documentation for usage.
