### ISSUE TITLE
Audio Mix Option-on/off toggle?

### ISSUE THREAD

**Issue by editormixer** [SteffeyDev/atemOSC#202]
should the Audio Mix option's on/off command be able to be controlled with a toggle button?
I've got it working by using 2 buttons, when it seems one should suffice, but can't get it to toggle-is there some specific language in the address that needs to be entered? Admittedly, I'm not a TouchOSC editor master...

**Comment by SteffeyDev** [comment]
This sounds like a good idea, I'll work on an on/off toggle and AFV toggle

**Comment by SteffeyDev** [comment]
So adding two toggles is strange because technically mix is a three value option.  What I'm going to try instead is using three toggle buttons, one for each value (on, off, afv), set up in such a way that when one is toggled on, the other two are toggled off.  Will this work for your needs @editormixer?  In TouchOSC, it would be set up so that you just have three toggle buttons per input, one for each, with local feedback toggled off.  The addresses would be `/atem/audio/input/<number>/mix/on`, `/atem/audio/input/<number>/mix/off`, and `/atem/audio/input/<number>/mix/afv`

**Comment by ruebyi** [comment]
So "off" should switch of "on" and "afv", correct? 
And and "afv" Button should toggle between "AFVon" and "AFVoff", correct?

**Comment by SteffeyDev** [comment]
Ok not even close, there's no such thing as AFVon and AFVoff. The switcher only supports three values. Either on (audio included in output), off (audio not included in output), or afv(audio included in output when camera is live).  These are mutually exclusive options, so turning one on implies the other two are not.

**Comment by ruebyi** [comment]
Ok, i understand! That’s fine

**Comment by SteffeyDev** [comment]
Ok, I added additional feedback for mix option, if you add 3 toggle buttons with the addresses I mentioned above and turn off local feedback, you should find that they work as a group.
