### ISSUE TITLE
atemOSC does not start automatically as Login Item

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#225]
I assign atemOSC in Login Items to automatically open (Mac Big Sur). Since version 4, the app no longer starts up automatically when launched this way. I have to quit atemOSC and restart to activate. For those who use atemOSC regularly and like to place atemOSC in Login Items, while not an earth shattering bug, this is a bit of an inconvenience. 

Peter, I mentioned this before, wondering if it can be fixed? 

Thanks!

Randall

**Comment by SteffeyDev** [comment]
This is a hard one to work on, as after every change I would have to redeploy locally and restart my computer.  I made a small change in 4.2.0, let me know if this is still an issue (I expect it to be, but you never know).

**Comment by c434techteam** [comment]
What's interesting is I have seen this too, but yesterday it launched automatically after rebooting the machine and it didn't show the switcher, port or anything, but it was still working, as I was receiving messages from OSCulator and it was processing them. I still closed it out and reopened it and it functioned as normal. So that must be the order of UI things you referenced in #260

**Comment by SteffeyDev** [comment]
Yes, it's definitely a UI issue, which means that the app technically should still work even though nothing shows in the UI

**Comment by SteffeyDev** [comment]
I've released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0), please test on that and open a support request at www.atemosc.com/support if it still doesn't open at login.
