### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by danielbuechele** [SteffeyDev/atemOSC#46]
As discussed in #36 a small website would be great for this project.
I would love to hear your thoughts. @iamjohnbarker

**Comment by iamjohnbarker** [comment]
I think a website would be excellent. it should include the following...

- Homepage with an explanation of what atemOSC is and does.
- Download links to the latest version and past version.
- A docs section that explains how to get started and use the atemOSC.
- Perhaps a contact form for assistance (i'm happy to be "customer service" depending on a number of emails that come in 😉)

Something I have found from YouTube comments and other sources is that people want to use it, but have trouble getting started - so an extensive docs section would be the best thing to spend energy on.

As for how/where to build it - I've built out sites with Squarespace before, but perhaps someone has a better solution in mind. Free/cheap would be of course preferred!

**Comment by danielbuechele** [comment]
Sounds good! I think Github pages is the best way to do this. I will set up a simple Travis script for deployment.
I like all of your ideas for the site! Perhaps we could add a section about different use cases as well (Osculator, Korg nano control, QLab, TouchOSC...)
In what way do you want to contribute? Creating a design? Structuring content? Coding the page? I am excited for any help.

**Comment by iamjohnbarker** [comment]
Absolutely, docs for using with midi keyboards and TouchOSC would all be perfect.

I'm happy to do all of the above. I can take on the creation, content, and design of the site and any input would be welcomed for sure.

Excited to give back to a much-used solution in my setup!

**Comment by danielbuechele** [comment]
Great! I added a basic setup of the website using Twitter's Bootstrap, but feel free to change however you like it.
The website is auto-deployed to Github Pages: http://danielbuechele.github.io/atemOSC/
I am using Travis for deployment, the website is deployed as soon as changes are merged into master.

**Comment by danielbuechele** [comment]
@iamjohnbarker any updates on this?

**Comment by iamjohnbarker** [comment]
@danielbuechele Made some good progress today on it (sorry for the delay but lots came up!).

I've just added a pull request #56

**Comment by danielbuechele** [comment]
Cool, here is the latest version: http://danielbuechele.github.io/atemOSC/

**Comment by SteffeyDev** [comment]
Thanks for working on this @iamjohnbarker!  A few suggestions, if I may:

1) Under Getting Started, you say "Once downloaded, unzip the file and copy it over to your applications folder."  You may want to be a bit more detailed here, because they are actually unzipping a folder, and don't want to copy the entire folder over to the applications folder, but just the `.app` file.
2) Very minor, but maybe change "atemOSC will connect." in the same section to "atemOSC will connect automatically."?  Only because it feels like a fragment and not an actual sentence.
3) Under the FAQ, question: "It's not working for me", I would link to the issues page as a second option (if they are putting in a valid IP address and it's still not working). Maybe even a short instruction of how to open an issue.  Currently it feels like if the issue is not the IP address being incorrect, there is nothing else they can do.

I know this is a first version so some of this I'm sure you were planning on changing anyways, and just didn't get to it yet.  Thanks again!

**Comment by danielbuechele** [comment]
One problem we should definitely mention is the version of the switcher firmware. Sometimes people running very old versions on their switcher, which causes the app not to connect.

**Comment by iamjohnbarker** [comment]
@SteffeyDev Excellent feedback - I've included this in my next working version. It's funny how I always thin my written English is good until I actually start writing haha.

@danielbuechele I'll add that for sure, but we'll have to be sure to keep the website updated when new versions are released!

**Comment by iamjohnbarker** [comment]
Lots more tweaks and content added to the website in #59. 

Happy to take on feedback as it was a lot of stuff to add and my eyes hurt a little now 🙄

**Comment by SteffeyDev** [comment]
@danielbuechele Probably need to update the project description, your SquareSpace link is expired.  Also, need to update the website from the readme changes introduced in #75.
